apiVersion: apps/v1
kind: Deployment # Deployment kommer att se till containers skapas 
metadata:
  name: staticwebserver
  namespace: yatest
  labels:
    app: staticwebserver
spec:
  replicas: 3 #scale out!!!!
  selector:
    matchLabels:
      app: staticwebserver
  template:
    metadata:
      labels:
        app: staticwebserver
    spec:
      containers:
        - name: staticwebserver
          image: git.systementor.se/yacloud/ya0412
          ports:
            - containerPort: 8080
          env:
            - name: RUNENVIRONMENT
              value: Production
---
apiVersion: v1
kind: Service
metadata:
  namespace: yatest
  name: staticwebserver-service
  labels:
    app: staticwebserver
spec:
  type: LoadBalancer # LoadBalancer skapar en extern IP-adress som kan nås från internet
  ports:
  - name: http
    port: 80 # 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: staticwebserver
  sessionAffinity: None